const constants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_ERROR: "LOGIN_REQUEST_ERROR",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_REQUEST_SUCCESS: "SIGN_UP_REQUEST_SUCCESS",
  SIGN_UP_REQUEST_ERROR: "SIGN_UP_REQUEST_ERROR",

  PROFILE_REQUEST: "PROFILE_REQUEST",
  PROFILE_REQUEST_SUCCESS: "PROFILE_REQUEST_SUCCESS",
  PROFILE_REQUEST_ERROR: "PROFILE_REQUEST_ERROR",
  DNA_FILE_UPLOAD: "DNA_FILE_UPLOAD",
  DNA_FILE_DELETE: "DNA_FILE_DELETE",

  FRIENDS_FAMILY_REQUEST: "FRIENDS_FAMILY_REQUEST",
  FRIENDS_FAMILY_REQUEST_SUCCESS: "FRIENDS_FAMILY_REQUEST_SUCCESS",
  FRIENDS_FAMILY_REQUEST_ERROR: "FRIENDS_FAMILY_REQUEST_ERROR",

  GET_FRIEND_DETAILS: "GET_FRIEND_DETAILS",
  GET_FRIEND_DETAILS_SUCCESS: "GET_FRIEND_DETAILS_SUCCESS",
  GET_FRIEND_DETAILS_ERROR: "GET_FRIEND_DETAILS_ERROR",
  GET_CHAT_MESSAGE_LIST: "GET_CHAT_MESSAGE_LIST",
  GET_CHAT_MESSAGE_LIST_SUCCESSS: "GET_CHAT_MESSAGE_LIST_SUCCESSS",
  GET_CHAT_MESSAGE_LIST_ERROR: "GET_CHAT_MESSAGE_LIST_ERROR",
  POST_CHAT_MESSAGE: "POST_CHAT_MESSAGE",
  POST_CHAT_MESSAGE_SUCCESS: "POST_CHAT_MESSAGE_SUCCESS",
  POST_CHAT_MESSAGE_ERROR: "POST_CHAT_MESSAGE_ERROR",
  RESET_PROFILE: "RESET_PROFILE",

  LOG_OUT: "LOG_OUT"
};

export default constants;
