const constants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_ERROR: "LOGIN_REQUEST_ERROR",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_REQUEST_SUCCESS: "SIGN_UP_REQUEST_SUCCESS",
  SIGN_UP_REQUEST_ERROR: "SIGN_UP_REQUEST_ERROR",

  PROFILE_REQUEST: "PROFILE_REQUEST",
  PROFILE_REQUEST_SUCCESS: "PROFILE_REQUEST_SUCCESS",
  PROFILE_REQUEST_ERROR: "PROFILE_REQUEST_ERROR",

  LOG_OUT: "LOG_OUT"
};

export default constants;
